간단한 머신러닝
- 인코딩, 정규화
- randomforest
- 가능하다면, cnn, lstm 적용

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split


import matplotlib as plt

In [2]:
tdf = pd.DataFrame(pd.read_csv('./total_thermal.csv', index_col=0, header=0))

tdf = tdf.drop(columns=['timestamp', 'etc_1', 'etc_2'])
print(tdf.shape)
tdf.head()

(10186, 66)


C:\Users\Administrator\AppData\Local\Temp\ipykernel_1756\3528058753.py:1: DtypeWarning: Columns (69) have mixed types. Specify dtype option on import or set low_memory=False.
  tdf = pd.DataFrame(pd.read_csv('./total_thermal.csv', index_col=0, header=0))


sensor_degree  thermal_00  thermal_01  thermal_02  thermal_03  \
True                                                                  
0            29.625       24.50       24.50       24.25       25.00   
1            29.625       24.00       24.75       24.50       25.00   
2            29.625       24.25       24.00       24.00       25.00   
3            29.625       23.50       24.25       24.25       24.75   
4            29.625       23.50       24.50       24.75       25.25   

      thermal_04  thermal_05  thermal_06  thermal_07  thermal_08  ...  \
True                                                              ...   
0          25.50       24.75       24.25       25.50       25.25  ...   
1          25.25       25.00       24.50       25.50       25.25  ...   
2          24.50       24.25       24.25       25.25       25.00  ...   
3          24.25       24.25       24.25       25.75       24.75  ...   
4          25.00       24.75       24.50       25.25       25.00  ...   

      thermal_55  thermal_56  thermal_57  thermal_58  thermal_59  thermal_60  \
True                                                                           
0          23.75       25.25       24.50       25.25       24.75       25.75   
1          24.25       25.00       24.75       25.75       25.00       25.25   
2          23.75       24.50       23.50       24.50       25.00       25.00   
3          24.50       24.75       25.00       24.75       25.00       24.75   
4          23.50       24.75       24.50       25.25       25.00       25.50   

      thermal_61  thermal_62  thermal_63   staus  
True                                              
0          26.25       23.75       24.50  heater  
1          25.25       24.25       24.75  heater  
2          25.25       24.00       23.75  heater  
3          25.50       23.50       23.75  heater  
4          25.75       24.25       23.50  heater  

[5 rows x 66 columns]

In [3]:
tdf.loc[tdf['staus']=='heater', :]

sensor_degree  thermal_00  thermal_01  thermal_02  thermal_03  \
True                                                                  
0            29.625       24.50       24.50       24.25       25.00   
1            29.625       24.00       24.75       24.50       25.00   
2            29.625       24.25       24.00       24.00       25.00   
3            29.625       23.50       24.25       24.25       24.75   
4            29.625       23.50       24.50       24.75       25.25   
...             ...         ...         ...         ...         ...   
2074         29.375       24.50       24.75       24.50       25.00   
2075         29.375       25.00       24.25       24.50       25.00   
2076         29.375       24.00       24.25       24.75       24.50   
2077         29.375       24.50       25.00       24.25       24.00   
2078         29.375       24.50       24.50       24.50       24.25   

      thermal_04  thermal_05  thermal_06  thermal_07  thermal_08  ...  \
True                                                              ...   
0          25.50       24.75       24.25       25.50       25.25  ...   
1          25.25       25.00       24.50       25.50       25.25  ...   
2          24.50       24.25       24.25       25.25       25.00  ...   
3          24.25       24.25       24.25       25.75       24.75  ...   
4          25.00       24.75       24.50       25.25       25.00  ...   
...          ...         ...         ...         ...         ...  ...   
2074       24.50       24.75       23.75       25.25       25.00  ...   
2075       25.00       24.50       23.50       25.75       24.75  ...   
2076       24.00       24.25       24.25       25.25       25.00  ...   
2077       24.75       24.75       24.00       25.00       25.00  ...   
2078       24.50       24.00       24.25       23.75       25.00  ...   

      thermal_55  thermal_56  thermal_57  thermal_58  thermal_59  thermal_60  \
True                                                                           
0          23.75       25.25       24.50       25.25       24.75       25.75   
1          24.25       25.00       24.75       25.75       25.00       25.25   
2          23.75       24.50       23.50       24.50       25.00       25.00   
3          24.50       24.75       25.00       24.75       25.00       24.75   
4          23.50       24.75       24.50       25.25       25.00       25.50   
...          ...         ...         ...         ...         ...         ...   
2074       24.25       24.75       24.50       25.25       25.75       25.25   
2075       24.75       26.00       25.25       25.75       25.50       25.50   
2076       25.25       26.00       25.50       25.25       25.50       25.75   
2077       24.50       26.25       25.25       25.25       25.75       25.50   
2078       24.50       25.25       25.00       25.50       25.50       25.50   

      thermal_61  thermal_62  thermal_63   staus  
True                                              
0          26.25       23.75       24.50  heater  
1          25.25       24.25       24.75  heater  
2          25.25       24.00       23.75  heater  
3          25.50       23.50       23.75  heater  
4          25.75       24.25       23.50  heater  
...          ...         ...         ...     ...  
2074       25.75       24.00       24.50  heater  
2075       25.50       25.00       24.50  heater  
2076       25.25       24.00       25.75  heater  
2077       25.25       24.75       24.75  heater  
2078       25.25       24.00       24.00  heater  

[2079 rows x 66 columns]

In [4]:
tdf.insert(65, 'avg', 0, allow_duplicates=False )
for x in range(len(tdf.index)):
    tdf.iloc[x, 65] = round(tdf.iloc[x,1:65].mean(),2)
tdf = tdf.loc[tdf['staus']!='heater', :]
tdf.head()
tdf.shape


C:\Users\Administrator\AppData\Local\Temp\ipykernel_1756\2521991355.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '24.55' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  tdf.iloc[x, 65] = round(tdf.iloc[x,1:65].mean(),2)


(8107, 67)

In [5]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import RobustScaler, MinMaxScaler

In [6]:
l_ecd = LabelEncoder()
tdf['staus'] = l_ecd.fit_transform(tdf['staus'])
tdf['staus'].unique()

array([0, 1, 2])

In [7]:
tdf.iloc[:,:-1]

sensor_degree  thermal_00  thermal_01  thermal_02  thermal_03  \
True                                                                   
2079         29.5000       24.25       24.50       24.50       25.50   
2080         29.5625       24.50       25.50       25.00       25.25   
2081         29.5000       25.50       25.25       25.00       25.75   
2082         29.5625       25.25       25.00       24.75       25.75   
2083         29.5000       25.00       25.00       25.50       25.75   
...              ...         ...         ...         ...         ...   
10181        29.5625       23.75       24.75       24.25       24.75   
10182        29.5625       23.50       23.75       23.50       24.75   
10183        29.5000       22.25       24.25       24.25       24.75   
10184        29.5000       23.75       23.25       23.75       24.50   
10185        29.5000       23.00       23.25       23.50       24.00   

       thermal_04  thermal_05  thermal_06  thermal_07  thermal_08  ...  \
True                                                               ...   
2079        25.00       25.00       24.25       25.75       25.50  ...   
2080        25.50       25.25       25.00       25.75       25.75  ...   
2081        25.50       25.75       25.00       25.50       26.00  ...   
2082        25.25       25.75       25.00       26.00       26.00  ...   
2083        25.50       25.25       25.50       26.00       26.00  ...   
...           ...         ...         ...         ...         ...  ...   
10181       24.75       24.50       23.75       25.25       23.75  ...   
10182       24.25       24.25       24.50       25.50       25.50  ...   
10183       24.25       24.00       24.00       24.25       24.50  ...   
10184       24.25       24.50       23.50       24.00       24.50  ...   
10185       24.00       24.00       23.00       24.25       24.50  ...   

       thermal_55  thermal_56  thermal_57  thermal_58  thermal_59  thermal_60  \
True                                                                            
2079        23.75       25.75       25.00       25.50       25.25       25.75   
2080        24.25       25.50       25.50       26.25       25.75       26.00   
2081        24.50       25.50       25.75       25.75       25.25       26.00   
2082        24.75       25.25       25.25       26.00       25.75       25.75   
2083        24.25       26.00       25.50       25.25       25.25       26.25   
...           ...         ...         ...         ...         ...         ...   
10181       24.75       25.25       25.50       26.00       25.75       25.25   
10182       24.25       25.25       24.75       25.25       25.75       25.75   
10183       24.75       25.00       25.00       25.25       25.75       25.75   
10184       24.50       25.00       25.25       25.75       26.25       25.50   
10185       24.50       25.25       24.50       25.00       25.50       25.75   

       thermal_61  thermal_62  thermal_63    avg  
True                                              
2079        25.75       24.00       24.75  24.67  
2080        25.50       24.25       23.75  25.06  
2081        26.00       25.00       24.25  25.15  
2082        26.25       24.00       24.75  25.11  
2083        26.25       24.50       24.75  25.10  
...           ...         ...         ...    ...  
10181       26.25       24.75       25.50  24.45  
10182       25.50       24.25       24.25  24.41  
10183       25.25       24.25       25.50  24.30  
10184       25.75       24.25       25.50  24.31  
10185       26.25       24.75       24.75  24.09  

[8107 rows x 66 columns]

In [8]:
rscaler = MinMaxScaler()
tdf.iloc[:,:-1] = rscaler.fit_transform(tdf.iloc[:,:-1])

In [9]:
tdf.head()

sensor_degree  thermal_00  thermal_01  thermal_02  thermal_03  \
True                                                                  
2079           0.50    0.523810    0.500000    0.421053    0.526316   
2080           0.75    0.571429    0.722222    0.526316    0.473684   
2081           0.50    0.761905    0.666667    0.526316    0.578947   
2082           0.75    0.714286    0.611111    0.473684    0.578947   
2083           0.50    0.666667    0.611111    0.631579    0.578947   

      thermal_04  thermal_05  thermal_06  thermal_07  thermal_08  ...  \
True                                                              ...   
2079    0.473684    0.476190        0.40    0.555556    0.526316  ...   
2080    0.578947    0.523810        0.55    0.555556    0.578947  ...   
2081    0.578947    0.619048        0.55    0.500000    0.631579  ...   
2082    0.526316    0.619048        0.55    0.611111    0.631579  ...   
2083    0.578947    0.523810        0.65    0.611111    0.631579  ...   

      thermal_56  thermal_57  thermal_58  thermal_59  thermal_60  thermal_61  \
True                                                                           
2079    0.451613    0.380952    0.380952        0.35    0.380952        0.36   
2080    0.419355    0.476190    0.523810        0.45    0.428571        0.32   
2081    0.419355    0.523810    0.428571        0.35    0.428571        0.40   
2082    0.387097    0.428571    0.476190        0.45    0.380952        0.44   
2083    0.483871    0.476190    0.333333        0.35    0.476190        0.44   

      thermal_62  thermal_63       avg  staus  
True                                           
2079    0.269231    0.407407  0.416667      0  
2080    0.307692    0.259259  0.528736      0  
2081    0.423077    0.333333  0.554598      0  
2082    0.269231    0.407407  0.543103      0  
2083    0.346154    0.407407  0.540230      0  

[5 rows x 67 columns]

In [10]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

In [11]:
from sklearn.utils.discovery import *
from sklearn.metrics import *
import warnings
rets=all_estimators(type_filter='classifier')

In [12]:
train_data = tdf.iloc[:,:-1]
print(train_data.head())
train_label = tdf.iloc[:,-1]
print(train_label.head())

      sensor_degree  thermal_00  thermal_01  thermal_02  thermal_03  \
True                                                                  
2079           0.50    0.523810    0.500000    0.421053    0.526316   
2080           0.75    0.571429    0.722222    0.526316    0.473684   
2081           0.50    0.761905    0.666667    0.526316    0.578947   
2082           0.75    0.714286    0.611111    0.473684    0.578947   
2083           0.50    0.666667    0.611111    0.631579    0.578947   

      thermal_04  thermal_05  thermal_06  thermal_07  thermal_08  ...  \
True                                                              ...   
2079    0.473684    0.476190        0.40    0.555556    0.526316  ...   
2080    0.578947    0.523810        0.55    0.555556    0.578947  ...   
2081    0.578947    0.619048        0.55    0.500000    0.631579  ...   
2082    0.526316    0.619048        0.55    0.611111    0.631579  ...   
2083    0.578947    0.523810        0.65    0.611111    0.631579

In [13]:
# result=[]
# for name, estimator_ in rets:
#     try:
#         model=estimator_()
#         if 'Logistic' in name or 'SGD' in name or 'MLP' in name:
#             model.set_params(max_iter=10000)
#         if 'SV' in name:
#             model.set_params(max_iter=100000, dual='auto')   
 
#         model.fit(train_data, train_label)
#         sc=model.score(train_data, train_label)
#         result.append((name, round(sc, 2)))
#     except Exception:
#         pass

In [14]:
# sorted(result, key=lambda x : x[1], reverse=True)
X_train, X_test, y_train, y_test =train_test_split(train_data,train_label)

In [15]:
def train_result(model):
    
    name = (str(model.__class__)).split('.')[3]
    # 학습
    model.fit(X_train, y_train)
    
    # 훈련 데이터와 테스트 데이터에서 정확도 계산
    train_score = model.score(X_train, y_train)
    test_score = model.score(X_test, y_test)

    # 예측값 계산
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    
    # 정확도 차이 계산
    diff = train_score - test_score
    
    # 평가 지표
    train_accuracy = accuracy_score(y_train, y_train_pred)
    test_accuracy = accuracy_score(y_test, y_test_pred)
    
    # F1-Score 등 더 상세한 평가 지표
    train_classification_report = classification_report(y_train, y_train_pred)
    test_classification_report = classification_report(y_test, y_test_pred)
    
    # 혼동 행렬
    train_confusion_matrix = confusion_matrix(y_train, y_train_pred)
    test_confusion_matrix = confusion_matrix(y_test, y_test_pred)
    
    # 결과 데이터프레임 준비
    resultDF = pd.DataFrame(columns=['train_score', 'test_score', 'diff', 
                                    'train_accuracy', 'test_accuracy'] )
                                    # 'train_classification_report', 'test_classification_report',
                                    # 'train_confusion_matrix', 'test_confusion_matrix'])
    resultDF.loc[name] = [train_score, test_score, diff, 
                            train_accuracy, test_accuracy]
    print('train_classification_report')
    print(train_classification_report)
    print('test_classification_report')
    print(test_classification_report)
    print('train_confusion_matrix')
    print(train_confusion_matrix)
    print('test_confusion_matrix')
    print(test_confusion_matrix)
    
    return model, resultDF

In [16]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
def gridCV_(model, param):
    ## 교차검증 및 튜닝 진행 인스턴스 생성
    # GridSearchCV는 모든 파라미터 조합을 시도합니다.
    # cv: 교차 검증 폴드 수 (일반적으로 3, 5, 10 등)
    # n_jobs: 병렬 처리할 작업 수 (-1은 모든 코어 사용)
    # verbose: 진행 상황 출력 레벨 (0: 출력 안 함, 1: 간략하게, 2: 상세하게)
    # error_score: 에러 발생 시 처리 방법 ('raise' 또는 특정 숫자)
    gridCV = GridSearchCV(model, param, refit=True, cv=5, n_jobs=-1, verbose=2, error_score='raise')
    print("구성된 하이퍼파라미터 탐색 범위:")
    for key, value in param.items():
        print(f"- {key}: {value}")
        
    gridCV.fit(X_train, y_train) # 학습 데이터로 최적의 파라미터를 찾습니다.
    print("--- GridSearchCV 모델 학습 완료 ---")
    print("-" * 30)

    # 4. 최적의 하이퍼파라미터 및 최고 성능 확인
    # -----------------------------------------------------------------------------
    print("\n--- 최적의 하이퍼파라미터 조합 ---")
    best_params = gridCV.best_params_
    print(best_params)

    print("\n--- 최적 모델의 교차 검증 최고 점수 ---")
    best_score = gridCV.best_score_
    print(f"정확도: {best_score:.4f}")
    print("-" * 30)

    # 5. 최적의 모델로 예측 및 성능 평가
    # -----------------------------------------------------------------------------
    # gridCV.best_estimator_에 refit=True 옵션 덕분에 최적의 파라미터로 학습된 모델이 저장됩니다.
    best_model = gridCV.best_estimator_

    print("\n--- 최적 모델로 테스트 데이터 예측 및 평가 ---")
    y_pred_test = best_model.predict(X_test)

    # 정확도
    test_accuracy = accuracy_score(y_test, y_pred_test)
    print(f"테스트 세트 정확도: {test_accuracy:.4f}")

    # 혼동 행렬
    test_confusion_matrix = confusion_matrix(y_test, y_pred_test)
    print("\n테스트 세트 혼동 행렬:")
    print(test_confusion_matrix)

    # 분류 보고서 (정밀도, 재현율, F1-스코어 등)
    test_classification_report = classification_report(y_test, y_pred_test)
    print("\n테스트 세트 분류 보고서:")
    print(test_classification_report)
    print("-" * 30)

    # 6. 결과 데이터프레임에 저장 (이전 질문의 코드 재활용)
    # -----------------------------------------------------------------------------
    # resultDF 초기화 (없을 경우 새로 생성)
    try:
        if not isinstance(resultDF, pd.DataFrame):
            raise NameError # DataFrame이 아니면 NameError 발생시켜 새로 생성
    except NameError:
        resultDF = pd.DataFrame(columns=['train_score', 'test_score', 'diff',
                                        'train_accuracy', 'test_accuracy',
                                        'train_classification_report', 'test_classification_report',
                                        'train_confusion_matrix', 'best_params']) # confusion_matrix는 dict 타입이 아니므로 주의
                                                                                # 여기서는 best_params를 추가함

    name = f"{str(model.__class__).split('.')[3]}_GridSearch_Best_{best_score:.4f}" # 모델 이름에 최고 점수 포함

    # GridSearchCV 결과에서 train_score는 gridCV.best_score_ (교차 검증 평균)가 됩니다.
    train_score_cv = gridCV.best_score_
    train_accuracy_cv = best_model.score(X_train, y_train) # 훈련 세트에서의 최종 모델 정확도

    diff = train_score_cv - test_accuracy

    # confusion matrix는 DataFrame에 직접 넣기보다 문자열로 변환하거나 별도로 저장하는 것이 좋습니다.
    # 여기서는 간단히 문자열로 변환합니다.
    test_confusion_matrix_str = str(test_confusion_matrix)
    # classification_report도 문자열로 변환합니다.
    train_classification_report_str = str(classification_report(y_train, best_model.predict(X_train)))
    test_classification_report_str = str(test_classification_report)


    resultDF.loc[name] = [train_score_cv, test_accuracy, diff,
                            train_accuracy_cv, test_accuracy,
                            train_classification_report_str, test_classification_report_str,
                            test_confusion_matrix_str, best_params]

    print("\n--- 결과 데이터프레임 (resultDF) ---")
    print(resultDF.transpose()) # 보기 좋게 전치하여 출력
    print("-" * 30)

In [17]:
param_dt = {
    # 불순도 측정 기준
    'criterion': ['gini', 'entropy', 'log_loss'],

    # 노드 분할 전략
    'splitter': ['best', 'random'],

    # 트리의 최대 깊이: 너무 깊으면 과적합, 너무 얕으면 과소적합.
    # 일반적으로 5 ~ 30 사이의 값을 많이 탐색합니다.
    'max_depth': [16, 24, 32], # 5부터 30까지의 정수 (포함)

    # 노드를 분할하기 위한 최소 샘플 수: int 또는 float
    # float인 경우 전체 샘플 수에 대한 비율
    # 'min_samples_split': [2, 4, 0.05, 0.1], # 정수 값과 비율을 함께 탐색
    'min_samples_split': [2, 4], # 정수 값과 비율을 함께 탐색

    # 리프 노드가 되기 위한 최소 샘플 수: int 또는 float
    # 'min_samples_leaf': [1, 2, 4, 0.01, 0.05], # 정수 값과 비율을 함께 탐색
    'min_samples_leaf': [1, 2, 4], # 정수 값과 비율을 함께 탐색

    # 리프 노드에 필요한 최소 가중치 샘플 비율
    'min_weight_fraction_leaf': [0.0, 0.001, 0.01],

    # 최적의 분할을 찾을 때 고려할 특성(feature)의 수
    # 'sqrt'는 sqrt(n_features)를 의미하며, 'log2'는 log2(n_features)를 의미
    'max_features': ['sqrt', 'log2'], # 'auto'는 1.1부터 'sqrt'와 동일 (현재는 'sqrt'로 리디렉션됨)
                                           # None은 모든 특성 사용

    # 리프 노드의 최대 개수
    # None은 제한 없음. 적절한 범위를 설정하여 탐색
    'max_leaf_nodes': [None, 20, 50, 100], # None과 함께 특정 숫자들을 탐색

    # 불순도 감소 최소량: 이 값보다 불순도 감소량이 작으면 노드 분할 중단
    'min_impurity_decrease': [0.005, 0.01, 0.02],

    # 복잡도 매개변수 (가지치기)
    'ccp_alpha': [0.01, 0.05] # 0.0은 가지치기 없음                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
}

## 모델 인스턴스 생성
dtmodel = DecisionTreeClassifier(random_state=42)

# gridCV_(dtmodel, param_dt)

In [18]:
dtCmodel = DecisionTreeClassifier(ccp_alpha= 0.01, criterion= 'gini', max_depth= 16, max_features= 'log2', max_leaf_nodes= 20, min_impurity_decrease= 0.005, min_samples_leaf= 1, min_samples_split= 2, min_weight_fraction_leaf= 0.0, splitter= 'best')
train_result(dtCmodel)


train_classification_report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00      1594
           1       0.00      0.00      0.00      1508
           2       0.49      1.00      0.66      2978

    accuracy                           0.49      6080
   macro avg       0.16      0.33      0.22      6080
weighted avg       0.24      0.49      0.32      6080

test_classification_report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       483
           1       0.00      0.00      0.00       519
           2       0.51      1.00      0.67      1025

    accuracy                           0.51      2027
   macro avg       0.17      0.33      0.22      2027
weighted avg       0.26      0.51      0.34      2027

train_confusion_matrix
[[   0    0 1594]
 [   0    0 1508]
 [   0    0 2978]]
test_confusion_matrix
[[   0    0  483]
 [   0    0  519]
 [   0    0 1025]]


c:\Users\Administrator\anaconda3\envs\test310\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Administrator\anaconda3\envs\test310\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Administrator\anaconda3\envs\test310\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitaliz

(DecisionTreeClassifier(ccp_alpha=0.01, max_depth=16, max_features='log2',
                        max_leaf_nodes=20, min_impurity_decrease=0.005),
                           train_score  test_score      diff  train_accuracy  \
 DecisionTreeClassifier'>     0.489803    0.505673 -0.015871        0.489803   
 
                           test_accuracy  
 DecisionTreeClassifier'>       0.505673  )

In [19]:
param_rf = {
    # Random Forest 고유 파라미터 ------------------------------------------------
    # 앙상블에 사용할 트리의 개수: 모델의 복잡도와 안정성에 영향
    'n_estimators': [500], # 일반적으로 100~500 사이의 값을 많이 탐색
                                         # 너무 크면 학습 시간이 오래 걸림

    # 부트스트랩 샘플링 사용 여부 (True가 기본값이며 일반적)
    'bootstrap': [True],

    # Decision Tree 파라미터 (Random Forest도 내부적으로 Decision Tree를 사용) -----------
    # 불순도 측정 기준
    'criterion': ['gini', 'entropy', 'log_loss'],

    # 트리의 최대 깊이: 너무 깊으면 과적합, 너무 얕으면 과소적합.
    # Random Forest는 개별 트리의 깊이보다는 트리의 개수가 더 중요할 수 있으나,
    # 깊이 제한을 통해 과적합 방지 및 속도 개선 가능
    'max_depth': [40, 50], # None은 제한 없음. 10단위로 탐색

    # 노드를 분할하기 위한 최소 샘플 수: int 또는 float (비율)
    'min_samples_split': [2, 5],

    # 리프 노드가 되기 위한 최소 샘플 수: int 또는 float (비율)
    'min_samples_leaf': [1, 2],

    # 최적의 분할을 찾을 때 고려할 특성(feature)의 수
    # 'sqrt'는 sqrt(n_features)를 의미 (기본값), 'log2'는 log2(n_features)를 의미
    # Random Forest는 무작위로 특성을 선택하여 다양성을 확보하므로 중요
    'max_features': ['sqrt', 'log2'], # 'auto'는 1.1부터 'sqrt'와 동일 (현재는 'sqrt'로 리디렉션됨)
                                           # None은 모든 특성 사용 (과적합 위험 증가)

    # 리프 노드의 최대 개수
    'max_leaf_nodes': [None, 20, 50, 100],

    # 불순도 감소 최소량: 이 값보다 불순도 감소량이 작으면 노드 분할 중단
    'min_impurity_decrease': [0.001, 0.002],

    # 복잡도 매개변수 (가지치기)
    'ccp_alpha': [0.001, 0.002] # 0.0은 가지치기 없음
}


## 모델 인스턴스 생성
rfmodel = RandomForestClassifier(random_state=42)

gridCV_(rfmodel, param_rf)

구성된 하이퍼파라미터 탐색 범위:
- n_estimators: [500]
- bootstrap: [True]
- criterion: ['gini', 'entropy', 'log_loss']
- max_depth: [40, 50]
- min_samples_split: [2, 5]
- min_samples_leaf: [1, 2]
- max_features: ['sqrt', 'log2']
- max_leaf_nodes: [None, 20, 50, 100]
- min_impurity_decrease: [0.001, 0.002]
- ccp_alpha: [0.001, 0.002]
Fitting 5 folds for each of 768 candidates, totalling 3840 fits


--- GridSearchCV 모델 학습 완료 ---
------------------------------

--- 최적의 하이퍼파라미터 조합 ---
{'bootstrap': True, 'ccp_alpha': 0.001, 'criterion': 'entropy', 'max_depth': 50, 'max_features': 'sqrt', 'max_leaf_nodes': None, 'min_impurity_decrease': 0.001, 'min_samples_leaf': 1, 'min_samples_split': 5, 'n_estimators': 500}

--- 최적 모델의 교차 검증 최고 점수 ---
정확도: 0.7039
------------------------------

--- 최적 모델로 테스트 데이터 예측 및 평가 ---
테스트 세트 정확도: 0.7262

테스트 세트 혼동 행렬:
[[234  24 225]
 [ 69 253 197]
 [ 20  20 985]]

테스트 세트 분류 보고서:
              precision    recall  f1-score   support

           0       0.72      0.48      0.58       483
           1       0.85      0.49      0.62       519
           2       0.70      0.96      0.81      1025

    accuracy                           0.73      2027
   macro avg       0.76      0.64      0.67      2027
weighted avg       0.74      0.73      0.71      2027

------------------------------

--- 결과 데이터프레임 (resultDF) ---
                               RandomForestCl

In [20]:
{'bootstrap': True, 'ccp_alpha': 0.001, 'criterion': 'entropy', 'max_depth': 40, 'max_features': 'sqrt', 'max_leaf_nodes': None, 'min_impurity_decrease': 0.001, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 500}


{'bootstrap': True,
 'ccp_alpha': 0.001,
 'criterion': 'entropy',
 'max_depth': 40,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.001,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'n_estimators': 500}

In [21]:
rfm50 = RandomForestClassifier(bootstrap= True, ccp_alpha= 0.0001, criterion= 'entropy', max_depth= 100, max_features= 'log2', max_leaf_nodes= None, min_impurity_decrease= 0.001, min_samples_leaf= 1, min_samples_split= 2, n_estimators= 1000)
best_rfm50, resultDF= train_result(rfm50)

train_classification_report
              precision    recall  f1-score   support

           0       1.00      0.88      0.94      1594
           1       1.00      0.96      0.98      1508
           2       0.93      1.00      0.96      2978

    accuracy                           0.96      6080
   macro avg       0.97      0.95      0.96      6080
weighted avg       0.96      0.96      0.96      6080

test_classification_report
              precision    recall  f1-score   support

           0       0.73      0.45      0.56       483
           1       0.87      0.48      0.62       519
           2       0.69      0.97      0.81      1025

    accuracy                           0.72      2027
   macro avg       0.76      0.63      0.66      2027
weighted avg       0.75      0.72      0.70      2027

train_confusion_matrix
[[1406    4  184]
 [   5 1452   51]
 [   0    0 2978]]
test_confusion_matrix
[[219  23 241]
 [ 64 249 206]
 [ 16  15 994]]


In [22]:
resultDF

train_score  test_score      diff  train_accuracy  \
RandomForestClassifier'>     0.959868    0.721263  0.238605        0.959868   

                          test_accuracy  
RandomForestClassifier'>       0.721263

In [23]:
rfm = RandomForestClassifier(bootstrap= True, ccp_alpha= 0.001, criterion= 'entropy', max_depth= 40, max_features= 'log2', max_leaf_nodes= None, min_impurity_decrease= 0.001, min_samples_leaf= 1, min_samples_split= 2, n_estimators= 500)
best_rfm, resultDF= train_result(rfm)


train_classification_report
              precision    recall  f1-score   support

           0       1.00      0.89      0.94      1594
           1       1.00      0.96      0.98      1508
           2       0.93      1.00      0.96      2978

    accuracy                           0.96      6080
   macro avg       0.97      0.95      0.96      6080
weighted avg       0.96      0.96      0.96      6080

test_classification_report
              precision    recall  f1-score   support

           0       0.75      0.46      0.57       483
           1       0.87      0.48      0.62       519
           2       0.69      0.97      0.81      1025

    accuracy                           0.72      2027
   macro avg       0.77      0.64      0.67      2027
weighted avg       0.75      0.72      0.70      2027

train_confusion_matrix
[[1411    5  178]
 [   5 1451   52]
 [   0    0 2978]]
test_confusion_matrix
[[222  24 237]
 [ 59 250 210]
 [ 14  14 997]]


In [24]:
resultDF

train_score  test_score     diff  train_accuracy  \
RandomForestClassifier'>     0.960526    0.724716  0.23581        0.960526   

                          test_accuracy  
RandomForestClassifier'>       0.724716

In [25]:
testData = pd.DataFrame(pd.read_csv('../thermal_data.csv', index_col=1))
testData = testData.drop(columns=['timestamp', 'etc_1', 'etc_2'])
print(testData.shape)
testData.insert(65, 'avg', 0, allow_duplicates=False )

(4709, 65)


In [26]:
testData.index

Index([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
       ...
       4700, 4701, 4702, 4703, 4704, 4705, 4706, 4707, 4708, 4709],
      dtype='int64', name='packet_id', length=4709)

In [27]:
testData.head()

sensor_degree  thermal_00  thermal_01  thermal_02  thermal_03  \
packet_id                                                                  
1                29.4375       24.75       24.75       25.25       25.00   
2                29.3750       24.00       24.75       24.25       25.25   
3                29.4375       24.50       24.25       24.75       25.00   
4                29.3750       22.75       24.25       24.25       24.50   
5                29.3750       24.00       23.75       24.50       24.75   

           thermal_04  thermal_05  thermal_06  thermal_07  thermal_08  ...  \
packet_id                                                              ...   
1               25.00       24.75       25.25       26.50       25.75  ...   
2               24.50       24.50       24.75       25.25       25.00  ...   
3               24.75       25.25       25.25       25.50       25.25  ...   
4               24.50       24.00       24.00       24.25       24.25  ...   
5               24.50       24.25       24.25       24.50       25.25  ...   

           thermal_55  thermal_56  thermal_57  thermal_58  thermal_59  \
packet_id                                                               
1               25.75       26.50       25.50       26.50       26.75   
2               26.00       27.25       26.00       26.75       26.75   
3               25.50       26.00       26.00       26.25       26.50   
4               25.25       26.00       26.00       26.75       26.50   
5               25.25       26.50       25.25       26.25       26.00   

           thermal_60  thermal_61  thermal_62  thermal_63  avg  
packet_id                                                       
1               26.75       27.50       25.75       26.25    0  
2               26.75       26.75       25.50       25.75    0  
3               26.75       27.00       25.25       26.00    0  
4               26.50       26.75       25.25       26.00    0  
5               26.25       26.75       25.50       26.00    0  

[5 rows x 66 columns]

In [28]:
testData.iloc[0, 0]

np.float64(29.4375)

In [29]:
for x in range(len(testData.index)):
    testData.iloc[x, 65] = round(testData.iloc[x,1:65].mean(),2)
testData.head()


C:\Users\Administrator\AppData\Local\Temp\ipykernel_1756\3206071764.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '25.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  testData.iloc[x, 65] = round(testData.iloc[x,1:65].mean(),2)


sensor_degree  thermal_00  thermal_01  thermal_02  thermal_03  \
packet_id                                                                  
1                29.4375       24.75       24.75       25.25       25.00   
2                29.3750       24.00       24.75       24.25       25.25   
3                29.4375       24.50       24.25       24.75       25.00   
4                29.3750       22.75       24.25       24.25       24.50   
5                29.3750       24.00       23.75       24.50       24.75   

           thermal_04  thermal_05  thermal_06  thermal_07  thermal_08  ...  \
packet_id                                                              ...   
1               25.00       24.75       25.25       26.50       25.75  ...   
2               24.50       24.50       24.75       25.25       25.00  ...   
3               24.75       25.25       25.25       25.50       25.25  ...   
4               24.50       24.00       24.00       24.25       24.25  ...   
5               24.50       24.25       24.25       24.50       25.25  ...   

           thermal_55  thermal_56  thermal_57  thermal_58  thermal_59  \
packet_id                                                               
1               25.75       26.50       25.50       26.50       26.75   
2               26.00       27.25       26.00       26.75       26.75   
3               25.50       26.00       26.00       26.25       26.50   
4               25.25       26.00       26.00       26.75       26.50   
5               25.25       26.50       25.25       26.25       26.00   

           thermal_60  thermal_61  thermal_62  thermal_63    avg  
packet_id                                                         
1               26.75       27.50       25.75       26.25  25.50  
2               26.75       26.75       25.50       25.75  25.23  
3               26.75       27.00       25.25       26.00  25.18  
4               26.50       26.75       25.25       26.00  24.81  
5               26.25       26.75       25.50       26.00  24.96  

[5 rows x 66 columns]

In [30]:
best_rfm.predict(testData.iloc[0,:].values.reshape(1,-1))

c:\Users\Administrator\anaconda3\envs\test310\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([2])