간단한 머신러닝
- 인코딩, 정규화
- randomforest
- 가능하다면, cnn, lstm 적용

In [78]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split


import matplotlib as plt

In [79]:
fdf = pd.DataFrame(pd.read_csv('./f24_hn_thermal.csv', index_col=0))
fdf.head()

C:\Users\Administrator\AppData\Local\Temp\ipykernel_11748\1625204550.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  fdf = pd.DataFrame(pd.read_csv('./f24_hn_thermal.csv', index_col=0))


status   mean  processed_pixel_0  processed_pixel_1  processed_pixel_2  \
0  human  24.28          24.521790          24.539282          24.584900   
1  human  24.19          24.687414          24.652172          24.569962   
2  human  24.15          24.504143          24.517320          24.550219   
3  human  24.10          24.773455          24.726620          24.618729   
4  human  24.03          24.333546          24.316872          24.277664   

   processed_pixel_3  processed_pixel_4  processed_pixel_5  processed_pixel_6  \
0          24.648350          24.719591          24.791016          24.856405   
1          24.476060          24.403406          24.361908          24.348406   
2          24.592878          24.635933          24.675793          24.712145   
3          24.498705          24.411907          24.368687          24.359528   
4          24.232134          24.195374          24.171410          24.157991   

   processed_pixel_7  ...  processed_pixel_566  processed_pixel_567  \
0          24.909521  ...            24.735065            24.674356   
1          24.359514  ...            25.028357            25.001467   
2          24.744528  ...            24.407175            24.353148   
3          24.374710  ...            24.535618            24.520256   
4          24.152800  ...            24.459860            24.448870   

   processed_pixel_568  processed_pixel_569  processed_pixel_570  \
0            24.571066            24.417990            24.221045   
1            24.889484            24.666780            24.357439   
2            24.276522            24.166860            24.026009   
3            24.486408            24.416975            24.310710   
4            24.405016            24.312033            24.177574   

   processed_pixel_571  processed_pixel_572  processed_pixel_573  \
0            23.997038            23.763195            23.545187   
1            24.026789            23.741127            23.541994   
2            23.866009            23.699280            23.544127   
3            24.179525            24.035790            23.897620   
4            24.029146            23.894750            23.793905   

   processed_pixel_574  processed_pixel_575  
0            23.383547            23.320324  
1            23.427300            23.390518  
2            23.429228            23.384321  
3            23.793253            23.751960  
4            23.731170            23.709585  

[5 rows x 578 columns]

In [80]:
max_pixel_values = fdf.iloc[:, 1:].max(axis=1).round(2)    
max_pixel_values = fdf.iloc[:, 1:].max(axis=1).round(2)    
min_pixel_values = fdf.iloc[:, 1:].min(axis=1).round(2)    
std_pixel_values = fdf.iloc[:, 1:].std(axis=1).round(2)    
var_pixel_values = fdf.iloc[:, 1:].var(axis=1).round(2)    



fdf.insert(2, 'max', max_pixel_values)
fdf.insert(3, 'min', min_pixel_values)
fdf.insert(3, 'std', std_pixel_values)
fdf.insert(3, 'var', var_pixel_values)

In [81]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import RobustScaler, MinMaxScaler

In [82]:
l_ecd = LabelEncoder()
fdf['status'] = l_ecd.fit_transform(fdf['status'])
fdf['status'].unique()

array([0, 1])

In [83]:
fdf.iloc[:,1:]

mean    max   var   std    min  processed_pixel_0  processed_pixel_1  \
0     24.28  25.20  0.13  0.36  23.32          24.521790          24.539282   
1     24.19  25.06  0.12  0.35  23.39          24.687414          24.652172   
2     24.15  24.99  0.10  0.31  23.38          24.504143          24.517320   
3     24.10  24.96  0.09  0.30  23.65          24.773455          24.726620   
4     24.03  24.80  0.07  0.26  23.52          24.333546          24.316872   
...     ...    ...   ...   ...    ...                ...                ...   
8091  24.08  24.97  0.12  0.34  23.00          24.521640          24.516607   
8092  23.92  24.75  0.18  0.42  22.79          24.286450          24.277988   
8093  23.97  24.80  0.16  0.40  22.85          24.802395          24.790930   
8094  23.83  24.83  0.15  0.39  22.38          24.533580          24.520033   
8095  24.04  24.82  0.11  0.34  22.86          24.823732          24.781193   

      processed_pixel_2  processed_pixel_3  processed_pixel_4  ...  \
0             24.584900          24.648350          24.719591  ...   
1             24.569962          24.476060          24.403406  ...   
2             24.550219          24.592878          24.635933  ...   
3             24.618729          24.498705          24.411907  ...   
4             24.277664          24.232134          24.195374  ...   
...                 ...                ...                ...  ...   
8091          24.514446          24.534565          24.593859  ...   
8092          24.270966          24.292913          24.367586  ...   
8093          24.760996          24.719288          24.672785  ...   
8094          24.488531          24.452784          24.425615  ...   
8095          24.685600          24.584991          24.523497  ...   

      processed_pixel_566  processed_pixel_567  processed_pixel_568  \
0               24.735065            24.674356            24.571066   
1               25.028357            25.001467            24.889484   
2               24.407175            24.353148            24.276522   
3               24.535618            24.520256            24.486408   
4               24.459860            24.448870            24.405016   
...                   ...                  ...                  ...   
8091            24.367437            24.319138            24.232092   
8092            23.895525            23.846733            23.744505   
8093            24.010084            24.023144            23.991516   
8094            23.864374            23.815363            23.723886   
8095            24.523136            24.460052            24.324257   

      processed_pixel_569  processed_pixel_570  processed_pixel_571  \
0               24.417990            24.221045            23.997038   
1               24.666780            24.357439            24.026789   
2               24.166860            24.026009            23.866009   
3               24.416975            24.310710            24.179525   
4               24.312033            24.177574            24.029146   
...                   ...                  ...                  ...   
8091            24.100056            23.925100            23.716188   
8092            23.567050            23.334623            23.102356   
8093            23.881235            23.696090            23.471207   
8094            23.568947            23.354870            23.106995   
8095            24.101927            23.813719            23.508907   

      processed_pixel_572  processed_pixel_573  processed_pixel_574  \
0               23.763195            23.545187            23.383547   
1               23.741127            23.541994            23.427300   
2               23.699280            23.544127            23.429228   
3               24.035790            23.897620            23.793253   
4               23.894750            23.793905            23.731170   
...                   ...                  ...                  ...   
8091          

In [84]:
rscaler = MinMaxScaler()
# rscaler = RobustScaler()
fdf.iloc[:,1:] = rscaler.fit_transform(fdf.iloc[:,1:])
fdf.head()

status      mean       max   var       std       min  processed_pixel_0  \
0       0  0.492593  0.366505  0.40  0.514286  0.514512           0.358606   
1       0  0.459259  0.332524  0.36  0.485714  0.532982           0.399777   
2       0  0.444444  0.315534  0.28  0.371429  0.530343           0.354219   
3       0  0.425926  0.308252  0.24  0.342857  0.601583           0.421165   
4       0  0.400000  0.269417  0.16  0.228571  0.567282           0.311812   

   processed_pixel_1  processed_pixel_2  processed_pixel_3  ...  \
0           0.373574           0.402630           0.409012  ...   
1           0.402449           0.398624           0.363421  ...   
2           0.367957           0.393329           0.394333  ...   
3           0.421492           0.411702           0.369413  ...   
4           0.316685           0.320235           0.298874  ...   

   processed_pixel_566  processed_pixel_567  processed_pixel_568  \
0             0.392584             0.383466             0.393328   
1             0.468033             0.468237             0.477187   
2             0.308235             0.300226             0.315756   
3             0.341277             0.343532             0.371032   
4             0.321788             0.325032             0.349597   

   processed_pixel_569  processed_pixel_570  processed_pixel_571  \
0             0.407872             0.391229             0.374292   
1             0.472557             0.424320             0.381113   
2             0.342578             0.343910             0.344247   
3             0.407608             0.412983             0.416135   
4             0.380323             0.380682             0.381654   

   processed_pixel_572  processed_pixel_573  processed_pixel_574  \
0             0.365623             0.368656             0.376720   
1             0.360691             0.367980             0.385454   
2             0.351339             0.368431             0.385839   
3             0.426542             0.443208             0.458508   
4             0.395023             0.421269             0.446114   

   processed_pixel_575  
0             0.380461  
1             0.394175  
2             0.392964  
3             0.464791  
4             0.456512  

[5 rows x 582 columns]

In [85]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.utils.discovery import *
from sklearn.metrics import *
import warnings
rets=all_estimators(type_filter='classifier')

In [86]:
train_data = fdf.iloc[:,1:]
print(train_data.head())
train_label = fdf.iloc[:,0]
print(train_label.head())

       mean       max   var       std       min  processed_pixel_0  \
0  0.492593  0.366505  0.40  0.514286  0.514512           0.358606   
1  0.459259  0.332524  0.36  0.485714  0.532982           0.399777   
2  0.444444  0.315534  0.28  0.371429  0.530343           0.354219   
3  0.425926  0.308252  0.24  0.342857  0.601583           0.421165   
4  0.400000  0.269417  0.16  0.228571  0.567282           0.311812   

   processed_pixel_1  processed_pixel_2  processed_pixel_3  processed_pixel_4  \
0           0.373574           0.402630           0.409012           0.421646   
1           0.402449           0.398624           0.363421           0.337030   
2           0.367957           0.393329           0.394333           0.399258   
3           0.421492           0.411702           0.369413           0.339305   
4           0.316685           0.320235           0.298874           0.281358   

   ...  processed_pixel_566  processed_pixel_567  processed_pixel_568  \
0  ...             

In [87]:
# ## find estimator
# result=[]
# for name, estimator_ in rets:
#     try:
#         model=estimator_()
#         if 'Logistic' in name or 'SGD' in name or 'MLP' in name:
#             model.set_params(max_iter=10000)
#         if 'SV' in name:
#             model.set_params(max_iter=100000, dual='auto')   
 
#         model.fit(train_data, train_label)
#         sc=model.score(train_data, train_label)
#         result.append((name, round(sc, 2)))
#     except Exception:
#         pass

In [88]:
# sorted(result, key=lambda x : x[1], reverse=True)
X_train, X_test, y_train, y_test =train_test_split(train_data,train_label)

In [89]:
def train_result(model):
    
    name = (str(model.__class__)).split('.')[3]
    # 학습
    model.fit(X_train, y_train)
    
    # 훈련 데이터와 테스트 데이터에서 정확도 계산
    train_score = model.score(X_train, y_train)
    test_score = model.score(X_test, y_test)

    # 예측값 계산
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    
    # 정확도 차이 계산
    diff = train_score - test_score
    
    # 평가 지표
    train_accuracy = accuracy_score(y_train, y_train_pred)
    test_accuracy = accuracy_score(y_test, y_test_pred)
    
    # F1-Score 등 더 상세한 평가 지표
    train_classification_report = classification_report(y_train, y_train_pred)
    test_classification_report = classification_report(y_test, y_test_pred)
    
    # 혼동 행렬
    train_confusion_matrix = confusion_matrix(y_train, y_train_pred)
    test_confusion_matrix = confusion_matrix(y_test, y_test_pred)
    
    # 결과 데이터프레임 준비
    resultDF = pd.DataFrame(columns=['train_score', 'test_score', 'diff', 
                                    'train_accuracy', 'test_accuracy'] )
                                    # 'train_classification_report', 'test_classification_report',
                                    # 'train_confusion_matrix', 'test_confusion_matrix'])
    resultDF.loc[name] = [train_score, test_score, diff, 
                            train_accuracy, test_accuracy]
    print('train_classification_report')
    print(train_classification_report)
    print('test_classification_report')
    print(test_classification_report)
    print('train_confusion_matrix')
    print(train_confusion_matrix)
    print('test_confusion_matrix')
    print(test_confusion_matrix)
    
    return model, resultDF

In [90]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
def gridCV_(model, param):
    ## 교차검증 및 튜닝 진행 인스턴스 생성
    # GridSearchCV는 모든 파라미터 조합을 시도합니다.
    # cv: 교차 검증 폴드 수 (일반적으로 3, 5, 10 등)
    # n_jobs: 병렬 처리할 작업 수 (-1은 모든 코어 사용)
    # verbose: 진행 상황 출력 레벨 (0: 출력 안 함, 1: 간략하게, 2: 상세하게)
    # error_score: 에러 발생 시 처리 방법 ('raise' 또는 특정 숫자)
    gridCV = GridSearchCV(model, param, refit=True, cv=5, n_jobs=-1, verbose=2, error_score='raise')
    print("구성된 하이퍼파라미터 탐색 범위:")
    for key, value in param.items():
        print(f"- {key}: {value}")
        
    gridCV.fit(X_train, y_train) # 학습 데이터로 최적의 파라미터를 찾습니다.
    print("--- GridSearchCV 모델 학습 완료 ---")
    print("-" * 30)

    # 4. 최적의 하이퍼파라미터 및 최고 성능 확인
    # -----------------------------------------------------------------------------
    print("\n--- 최적의 하이퍼파라미터 조합 ---")
    best_params = gridCV.best_params_
    print(best_params)

    print("\n--- 최적 모델의 교차 검증 최고 점수 ---")
    best_score = gridCV.best_score_
    print(f"정확도: {best_score:.4f}")
    print("-" * 30)

    # 5. 최적의 모델로 예측 및 성능 평가
    # -----------------------------------------------------------------------------
    # gridCV.best_estimator_에 refit=True 옵션 덕분에 최적의 파라미터로 학습된 모델이 저장됩니다.
    best_model = gridCV.best_estimator_

    print("\n--- 최적 모델로 테스트 데이터 예측 및 평가 ---")
    y_pred_test = best_model.predict(X_test)

    # 정확도
    test_accuracy = accuracy_score(y_test, y_pred_test)
    print(f"테스트 세트 정확도: {test_accuracy:.4f}")

    # 혼동 행렬
    test_confusion_matrix = confusion_matrix(y_test, y_pred_test)
    print("\n테스트 세트 혼동 행렬:")
    print(test_confusion_matrix)

    # 분류 보고서 (정밀도, 재현율, F1-스코어 등)
    test_classification_report = classification_report(y_test, y_pred_test)
    print("\n테스트 세트 분류 보고서:")
    print(test_classification_report)
    print("-" * 30)

    # 6. 결과 데이터프레임에 저장 (이전 질문의 코드 재활용)
    # -----------------------------------------------------------------------------
    # resultDF 초기화 (없을 경우 새로 생성)
    try:
        if not isinstance(resultDF, pd.DataFrame):
            raise NameError # DataFrame이 아니면 NameError 발생시켜 새로 생성
    except NameError:
        resultDF = pd.DataFrame(columns=['train_score', 'test_score', 'diff',
                                        'train_accuracy', 'test_accuracy',
                                        'train_classification_report', 'test_classification_report',
                                        'train_confusion_matrix', 'best_params']) # confusion_matrix는 dict 타입이 아니므로 주의
                                                                                # 여기서는 best_params를 추가함

    name = f"{str(model.__class__).split('.')[3]}_GridSearch_Best_{best_score:.4f}" # 모델 이름에 최고 점수 포함

    # GridSearchCV 결과에서 train_score는 gridCV.best_score_ (교차 검증 평균)가 됩니다.
    train_score_cv = gridCV.best_score_
    train_accuracy_cv = best_model.score(X_train, y_train) # 훈련 세트에서의 최종 모델 정확도

    diff = train_score_cv - test_accuracy

    # confusion matrix는 DataFrame에 직접 넣기보다 문자열로 변환하거나 별도로 저장하는 것이 좋습니다.
    # 여기서는 간단히 문자열로 변환합니다.
    test_confusion_matrix_str = str(test_confusion_matrix)
    # classification_report도 문자열로 변환합니다.
    train_classification_report_str = str(classification_report(y_train, best_model.predict(X_train)))
    test_classification_report_str = str(test_classification_report)


    resultDF.loc[name] = [train_score_cv, test_accuracy, diff,
                            train_accuracy_cv, test_accuracy,
                            train_classification_report_str, test_classification_report_str,
                            test_confusion_matrix_str, best_params]

    print("\n--- 결과 데이터프레임 (resultDF) ---")
    print(resultDF.transpose()) # 보기 좋게 전치하여 출력
    print("-" * 30)

In [91]:
dtCmodel = DecisionTreeClassifier(ccp_alpha= 0.01, criterion= 'gini', max_depth= 16, max_features= 'log2', max_leaf_nodes= 20, min_impurity_decrease= 0.005, min_samples_leaf= 1, min_samples_split= 2, min_weight_fraction_leaf= 0.0, splitter= 'best')
train_result(dtCmodel)


train_classification_report
              precision    recall  f1-score   support

           0       0.62      0.48      0.54      3000
           1       0.58      0.71      0.64      3072

    accuracy                           0.60      6072
   macro avg       0.60      0.59      0.59      6072
weighted avg       0.60      0.60      0.59      6072

test_classification_report
              precision    recall  f1-score   support

           0       0.60      0.44      0.51      1023
           1       0.55      0.70      0.62      1001

    accuracy                           0.57      2024
   macro avg       0.58      0.57      0.56      2024
weighted avg       0.58      0.57      0.56      2024

train_confusion_matrix
[[1444 1556]
 [ 900 2172]]
test_confusion_matrix
[[455 568]
 [301 700]]


(DecisionTreeClassifier(ccp_alpha=0.01, max_depth=16, max_features='log2',
                        max_leaf_nodes=20, min_impurity_decrease=0.005),
                           train_score  test_score      diff  train_accuracy  \
 DecisionTreeClassifier'>      0.59552    0.570652  0.024868         0.59552   
 
                           test_accuracy  
 DecisionTreeClassifier'>       0.570652  )

In [92]:
param_rf = {
    # Random Forest 고유 파라미터 ------------------------------------------------
    # 앙상블에 사용할 트리의 개수: 모델의 복잡도와 안정성에 영향
    'n_estimators': [500], # 일반적으로 100~500 사이의 값을 많이 탐색
                                         # 너무 크면 학습 시간이 오래 걸림

    # 부트스트랩 샘플링 사용 여부 (True가 기본값이며 일반적)
    'bootstrap': [True],

    # Decision Tree 파라미터 (Random Forest도 내부적으로 Decision Tree를 사용) -----------
    # 불순도 측정 기준
    'criterion': ['gini', 'entropy', 'log_loss'],

    # 트리의 최대 깊이: 너무 깊으면 과적합, 너무 얕으면 과소적합.
    # Random Forest는 개별 트리의 깊이보다는 트리의 개수가 더 중요할 수 있으나,
    # 깊이 제한을 통해 과적합 방지 및 속도 개선 가능
    'max_depth': [40, 80], # None은 제한 없음. 10단위로 탐색

    # 노드를 분할하기 위한 최소 샘플 수: int 또는 float (비율)
    'min_samples_split': [2, 5],

    # 리프 노드가 되기 위한 최소 샘플 수: int 또는 float (비율)
    'min_samples_leaf': [1, 2],

    # 최적의 분할을 찾을 때 고려할 특성(feature)의 수
    # 'sqrt'는 sqrt(n_features)를 의미 (기본값), 'log2'는 log2(n_features)를 의미
    # Random Forest는 무작위로 특성을 선택하여 다양성을 확보하므로 중요
    'max_features': ['sqrt', 'log2'], # 'auto'는 1.1부터 'sqrt'와 동일 (현재는 'sqrt'로 리디렉션됨)
                                           # None은 모든 특성 사용 (과적합 위험 증가)

    # 리프 노드의 최대 개수
    'max_leaf_nodes': [20, 50],

    # 불순도 감소 최소량: 이 값보다 불순도 감소량이 작으면 노드 분할 중단
    'min_impurity_decrease': [0.001, 0.002],

    # 복잡도 매개변수 (가지치기)
    'ccp_alpha': [0.001, 0.002] # 0.0은 가지치기 없음
}


## 모델 인스턴스 생성
rfmodel = RandomForestClassifier(random_state=42)

# gridCV_(rfmodel, param_rf)

In [93]:
param_rf = {
    # Random Forest 고유 파라미터 ------------------------------------------------
    # 앙상블에 사용할 트리의 개수: 모델의 복잡도와 안정성에 영향
    'n_estimators': [500], # 일반적으로 100~500 사이의 값을 많이 탐색
                                         # 너무 크면 학습 시간이 오래 걸림

    # 부트스트랩 샘플링 사용 여부 (True가 기본값이며 일반적)
    'bootstrap': [True],

    # Decision Tree 파라미터 (Random Forest도 내부적으로 Decision Tree를 사용) -----------
    # 불순도 측정 기준
    'criterion': ['gini', 'entropy', 'log_loss'],
    # 'criterion': ['gini'],

    # 트리의 최대 깊이: 너무 깊으면 과적합, 너무 얕으면 과소적합.
    # Random Forest는 개별 트리의 깊이보다는 트리의 개수가 더 중요할 수 있으나,
    # 깊이 제한을 통해 과적합 방지 및 속도 개선 가능
    'max_depth': [20, 40, 80], # None은 제한 없음. 10단위로 탐색

    # 노드를 분할하기 위한 최소 샘플 수: int 또는 float (비율)
    'min_samples_split': [2, 5],

    # 리프 노드가 되기 위한 최소 샘플 수: int 또는 float (비율)
    'min_samples_leaf': [1, 2],

    # 최적의 분할을 찾을 때 고려할 특성(feature)의 수
    # 'sqrt'는 sqrt(n_features)를 의미 (기본값), 'log2'는 log2(n_features)를 의미
    # Random Forest는 무작위로 특성을 선택하여 다양성을 확보하므로 중요
    'max_features': ['sqrt', 'log2'], # 'auto'는 1.1부터 'sqrt'와 동일 (현재는 'sqrt'로 리디렉션됨)
                                           # None은 모든 특성 사용 (과적합 위험 증가)

    # 리프 노드의 최대 개수
    'max_leaf_nodes': [20, 40],

    # 불순도 감소 최소량: 이 값보다 불순도 감소량이 작으면 노드 분할 중단
    'min_impurity_decrease': [0.001],

    # 복잡도 매개변수 (가지치기)
    'ccp_alpha': [0.001, 0.002] # 0.0은 가지치기 없음
}


## 모델 인스턴스 생성
rfmodel = RandomForestClassifier(random_state=42)

# gridCV_(rfmodel, param_rf)

In [94]:
{'bootstrap': True,
 'ccp_alpha': 0.001,
 'criterion': 'entropy',
 'max_depth': 40,
 'max_features': 'sqrt',
 'max_leaf_nodes': 40,
 'min_impurity_decrease': 0.001,
 'min_samples_leaf': 1,
 'min_samples_split': 5,
 'n_estimators': 500}

{'bootstrap': True,
 'ccp_alpha': 0.001,
 'criterion': 'entropy',
 'max_depth': 40,
 'max_features': 'sqrt',
 'max_leaf_nodes': 40,
 'min_impurity_decrease': 0.001,
 'min_samples_leaf': 1,
 'min_samples_split': 5,
 'n_estimators': 500}

In [95]:
rfm50 = RandomForestClassifier(bootstrap= True,
 ccp_alpha= 0.001,
 criterion= 'entropy',
 max_depth= 40,
 max_features= 'sqrt',
 max_leaf_nodes= 40,
 min_impurity_decrease= 0.001,
 min_samples_leaf= 1,
 min_samples_split= 5,
 n_estimators= 500)
best_rfm50, resultDF= train_result(rfm50)

train_classification_report
              precision    recall  f1-score   support

           0       0.90      0.77      0.83      3000
           1       0.81      0.91      0.86      3072

    accuracy                           0.84      6072
   macro avg       0.85      0.84      0.84      6072
weighted avg       0.85      0.84      0.84      6072

test_classification_report
              precision    recall  f1-score   support

           0       0.85      0.71      0.78      1023
           1       0.75      0.87      0.80      1001

    accuracy                           0.79      2024
   macro avg       0.80      0.79      0.79      2024
weighted avg       0.80      0.79      0.79      2024

train_confusion_matrix
[[2321  679]
 [ 264 2808]]
test_confusion_matrix
[[731 292]
 [132 869]]


In [96]:
resultDF

train_score  test_score      diff  train_accuracy  \
RandomForestClassifier'>     0.844697    0.790514  0.054183        0.844697   

                          test_accuracy  
RandomForestClassifier'>       0.790514

In [76]:
rfm  = RandomForestClassifier(
                            bootstrap = True, 
                            ccp_alpha = 0.001, 
                            criterion = 'gini', 
                            max_depth = 80, 
                            max_features = 'log2', 
                            max_leaf_nodes = 80, 
                            min_impurity_decrease = 0.001, 
                            min_samples_leaf = 1, 
                            min_samples_split = 2, 
                            n_estimators = 500)
best_rfm, resultDF = train_result(rfm)

train_classification_report
              precision    recall  f1-score   support

           0       0.94      0.83      0.88      3028
           1       0.85      0.94      0.89      3044

    accuracy                           0.89      6072
   macro avg       0.89      0.89      0.89      6072
weighted avg       0.89      0.89      0.89      6072

test_classification_report
              precision    recall  f1-score   support

           0       0.84      0.78      0.81       995
           1       0.80      0.85      0.83      1029

    accuracy                           0.82      2024
   macro avg       0.82      0.82      0.82      2024
weighted avg       0.82      0.82      0.82      2024

train_confusion_matrix
[[2508  520]
 [ 173 2871]]
test_confusion_matrix
[[774 221]
 [151 878]]


In [77]:
resultDF

train_score  test_score      diff  train_accuracy  \
RandomForestClassifier'>      0.88587    0.816206  0.069664         0.88587   

                          test_accuracy  
RandomForestClassifier'>       0.816206

In [ ]:
import joblib

# 가정: 여기에 'best_rfm' 이라는 변수에 저장하고자 하는 객체가 있습니다.
# 예를 들어, GridSearchCV나 RandomizedSearchCV를 통해 얻은 최적의 모델 객체일 수 있습니다.
# best_rfm = ... (예: grid_search.best_estimator_ 또는 직접 생성한 RFM 모델 객체)

# 저장할 파일 경로 및 이름 지정 (확장자는 보통 .pkl 또는 .joblib 사용)
file_path = 'f24_rfm_model.joblib'

# joblib.dump()를 사용하여 객체 저장
try:
    joblib.dump(best_rfm, file_path)
    print(f"'{file_path}'에 'best_rfm' 객체가 성공적으로 저장되었습니다.")
except Exception as e:
    print(f"객체 저장 중 오류 발생: {e}")

# 나중에 객체를 다시 불러오는 방법 (참고)
# try:
#     loaded_rfm = joblib.load(file_path)
#     print(f"'{file_path}'에서 'best_rfm' 객체가 성공적으로 로드되었습니다.")
#     # 로드된 객체 사용 예시
#     # print(loaded_rfm)
# except Exception as e:
#     print(f"객체 로드 중 오류 발생: {e}")

'f24_rfm_model083.joblib'에 'best_rfm' 객체가 성공적으로 저장되었습니다.


In [160]:
testData = pd.DataFrame(pd.read_csv('../thermal_data.csv', index_col=1))
testData = testData.drop(columns=['timestamp', 'etc_1', 'etc_2'])
print(testData.shape)
testData.insert(65, 'avg', 0, allow_duplicates=False )

(3621, 65)


In [161]:
testData.index

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       901, 902, 903, 904, 905, 906, 907, 908, 909, 910],
      dtype='int64', name='packet_id', length=3621)

In [162]:
testData.head()

sensor_degree  thermal_00  thermal_01  thermal_02  thermal_03  \
packet_id                                                                  
1                29.3125       23.75       25.25       25.00       25.50   
2                29.3125       24.50       23.75       25.25       25.00   
3                29.3125       24.75       24.50       24.75       25.25   
4                29.3125       24.75       24.25       24.50       25.50   
5                29.3125       23.50       24.25       24.25       24.50   

           thermal_04  thermal_05  thermal_06  thermal_07  thermal_08  ...  \
packet_id                                                              ...   
1               25.00       24.75       24.50       25.00       25.25  ...   
2               24.75       24.25       24.25       25.25       25.00  ...   
3               25.00       24.75       25.00       25.50       25.25  ...   
4               24.50       24.50       24.25       25.25       25.25  ...   
5               25.00       24.25       25.00       24.75       25.75  ...   

           thermal_55  thermal_56  thermal_57  thermal_58  thermal_59  \
packet_id                                                               
1               25.00       25.50       25.00       25.75       25.75   
2               24.50       26.00       25.50       25.75       25.75   
3               25.25       25.00       25.50       25.75       25.25   
4               25.25       26.25       26.00       26.25       26.25   
5               24.25       25.50       25.25       25.50       26.25   

           thermal_60  thermal_61  thermal_62  thermal_63  avg  
packet_id                                                       
1               26.00       25.75       24.50       24.25    0  
2               26.25       26.25       25.25       24.75    0  
3               25.50       26.75       25.25       24.75    0  
4               25.50       26.00       24.75       24.75    0  
5               25.25       26.00       24.50       25.00    0  

[5 rows x 66 columns]

In [163]:
testData.iloc[0, 0]

np.float64(29.3125)

In [164]:
for x in range(len(testData.index)):
    testData.iloc[x, 65] = round(testData.iloc[x,1:65].mean(),2)
testData.head()


C:\Users\Administrator\AppData\Local\Temp\ipykernel_10208\3206071764.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '24.87' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  testData.iloc[x, 65] = round(testData.iloc[x,1:65].mean(),2)


sensor_degree  thermal_00  thermal_01  thermal_02  thermal_03  \
packet_id                                                                  
1                29.3125       23.75       25.25       25.00       25.50   
2                29.3125       24.50       23.75       25.25       25.00   
3                29.3125       24.75       24.50       24.75       25.25   
4                29.3125       24.75       24.25       24.50       25.50   
5                29.3125       23.50       24.25       24.25       24.50   

           thermal_04  thermal_05  thermal_06  thermal_07  thermal_08  ...  \
packet_id                                                              ...   
1               25.00       24.75       24.50       25.00       25.25  ...   
2               24.75       24.25       24.25       25.25       25.00  ...   
3               25.00       24.75       25.00       25.50       25.25  ...   
4               24.50       24.50       24.25       25.25       25.25  ...   
5               25.00       24.25       25.00       24.75       25.75  ...   

           thermal_55  thermal_56  thermal_57  thermal_58  thermal_59  \
packet_id                                                               
1               25.00       25.50       25.00       25.75       25.75   
2               24.50       26.00       25.50       25.75       25.75   
3               25.25       25.00       25.50       25.75       25.25   
4               25.25       26.25       26.00       26.25       26.25   
5               24.25       25.50       25.25       25.50       26.25   

           thermal_60  thermal_61  thermal_62  thermal_63    avg  
packet_id                                                         
1               26.00       25.75       24.50       24.25  24.87  
2               26.25       26.25       25.25       24.75  24.85  
3               25.50       26.75       25.25       24.75  24.90  
4               25.50       26.00       24.75       24.75  24.88  
5               25.25       26.00       24.50       25.00  24.73  

[5 rows x 66 columns]

In [165]:
best_rfm.predict(testData.iloc[0,:].values.reshape(1,-1))

c:\Users\Administrator\anaconda3\envs\test310\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0])