간단한 머신러닝
- 인코딩, 정규화
- randomforest
- 가능하다면, cnn, lstm 적용

In [89]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split


import matplotlib as plt

In [90]:
tdf = pd.DataFrame(pd.read_csv('./total_thermal_noAC.csv', index_col=0, header=0))

tdf = tdf.drop(columns=['timestamp', 'etc_1', 'etc_2'])
print(tdf.shape)
tdf.head()

(10002, 66)


C:\Users\Administrator\AppData\Local\Temp\ipykernel_10208\2458045072.py:1: DtypeWarning: Columns (69) have mixed types. Specify dtype option on import or set low_memory=False.
  tdf = pd.DataFrame(pd.read_csv('./total_thermal_noAC.csv', index_col=0, header=0))


sensor_degree  thermal_00  thermal_01  thermal_02  thermal_03  \
True                                                                  
0           29.9375       25.75       25.25       25.25       25.75   
1           29.9375       25.00       24.75       24.75       25.50   
2           29.9375       25.25       25.25       25.50       25.75   
3           30.0000       26.00       25.75       25.25       26.00   
4           29.9375       26.25       25.75       25.50       26.00   

      thermal_04  thermal_05  thermal_06  thermal_07  thermal_08  ...  \
True                                                              ...   
0          25.75       24.50       24.75       24.75       25.25  ...   
1          25.00       25.00       24.75       26.25       25.50  ...   
2          25.75       25.50       25.75       26.25       25.00  ...   
3          25.50       25.25       25.75       25.50       25.50  ...   
4          25.00       25.50       25.75       26.00       25.75  ...   

      thermal_55  thermal_56  thermal_57  thermal_58  thermal_59  thermal_60  \
True                                                                           
0          23.50       24.50       50.75       42.50       25.25       24.75   
1          23.50       25.25       51.00       42.50       24.50       26.00   
2          23.25       24.75       51.25       42.75       25.00       25.75   
3          23.75       24.75       50.75       42.50       25.00       25.75   
4          23.50       24.75       50.25       42.75       25.25       26.00   

      thermal_61  thermal_62  thermal_63   staus  
True                                              
0          25.75       23.25       22.50  heater  
1          25.00       23.00       22.50  heater  
2          25.00       23.00       22.25  heater  
3          25.25       23.25       22.75  heater  
4          25.50       23.00       22.25  heater  

[5 rows x 66 columns]

In [91]:
tdf.loc[tdf['staus']=='heater', :]

sensor_degree  thermal_00  thermal_01  thermal_02  thermal_03  \
True                                                                  
0           29.9375       25.75       25.25       25.25       25.75   
1           29.9375       25.00       24.75       24.75       25.50   
2           29.9375       25.25       25.25       25.50       25.75   
3           30.0000       26.00       25.75       25.25       26.00   
4           29.9375       26.25       25.75       25.50       26.00   
...             ...         ...         ...         ...         ...   
1901        30.3750       24.75       23.75       24.25       24.75   
1902        30.4375       25.25       24.25       24.50       24.50   
1903        30.4375       24.25       24.00       24.25       24.75   
1904        30.4375       23.25       24.00       24.25       24.25   
1905        30.4375       24.25       24.25       23.75       24.50   

      thermal_04  thermal_05  thermal_06  thermal_07  thermal_08  ...  \
True                                                              ...   
0          25.75       24.50       24.75       24.75       25.25  ...   
1          25.00       25.00       24.75       26.25       25.50  ...   
2          25.75       25.50       25.75       26.25       25.00  ...   
3          25.50       25.25       25.75       25.50       25.50  ...   
4          25.00       25.50       25.75       26.00       25.75  ...   
...          ...         ...         ...         ...         ...  ...   
1901       24.50       24.00       23.50       24.00       25.75  ...   
1902       24.25       23.75       24.25       24.75       25.75  ...   
1903       24.25       24.00       23.50       24.50       25.50  ...   
1904       23.75       24.00       23.00       24.25       25.00  ...   
1905       24.25       24.50       23.75       24.50       25.75  ...   

      thermal_55  thermal_56  thermal_57  thermal_58  thermal_59  thermal_60  \
True                                                                           
0          23.50       24.50       50.75       42.50       25.25       24.75   
1          23.50       25.25       51.00       42.50       24.50       26.00   
2          23.25       24.75       51.25       42.75       25.00       25.75   
3          23.75       24.75       50.75       42.50       25.00       25.75   
4          23.50       24.75       50.25       42.75       25.25       26.00   
...          ...         ...         ...         ...         ...         ...   
1901       23.25       25.00       24.75       25.00       24.25       25.50   
1902       23.25       24.50       24.25       25.25       24.75       25.50   
1903       23.50       25.00       24.75       25.25       24.50       25.00   
1904       23.75       24.50       24.75       24.50       24.25       24.75   
1905       23.25       25.00       24.75       24.50       24.25       24.50   

      thermal_61  thermal_62  thermal_63   staus  
True                                              
0          25.75       23.25       22.50  heater  
1          25.00       23.00       22.50  heater  
2          25.00       23.00       22.25  heater  
3          25.25       23.25       22.75  heater  
4          25.50       23.00       22.25  heater  
...          ...         ...         ...     ...  
1901       25.00       23.25       23.75  heater  
1902       25.25       24.00       23.50  heater  
1903       25.25       23.50       24.25  heater  
1904       24.50       23.50       23.00  heater  
1905       25.50       23.00       24.25  heater  

[1906 rows x 66 columns]

In [92]:
tdf.insert(65, 'avg', 0, allow_duplicates=False )
for x in range(len(tdf.index)):
    tdf.iloc[x, 65] = round(tdf.iloc[x,1:65].mean(),2)
tdf = tdf.loc[tdf['staus']!='heater', :]
tdf.head()
tdf.shape


C:\Users\Administrator\AppData\Local\Temp\ipykernel_10208\2521991355.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '25.1' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  tdf.iloc[x, 65] = round(tdf.iloc[x,1:65].mean(),2)


(8096, 67)

In [93]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import RobustScaler, MinMaxScaler

In [94]:
l_ecd = LabelEncoder()
tdf['staus'] = l_ecd.fit_transform(tdf['staus'])
tdf['staus'].unique()

array([0, 1, 2])

In [95]:
tdf.iloc[:,:-1]

sensor_degree  thermal_00  thermal_01  thermal_02  thermal_03  \
True                                                                   
1906         29.8750       24.00       24.75       25.00       25.25   
1907         29.8750       24.75       24.50       24.25       24.50   
1908         29.8750       24.00       24.75       24.75       25.25   
1909         29.8750       24.75       24.50       24.25       24.50   
1910         29.8750       24.25       24.25       24.00       24.25   
...              ...         ...         ...         ...         ...   
9997         30.0625       24.25       24.50       25.25       25.25   
9998         30.0625       24.25       23.75       25.25       24.75   
9999         30.0625       24.75       25.00       24.50       25.00   
10000        30.0625       24.25       24.50       24.50       24.75   
10001        30.0625       25.00       24.50       24.50       25.00   

       thermal_04  thermal_05  thermal_06  thermal_07  thermal_08  ...  \
True                                                               ...   
1906        24.50       24.75       24.50       25.00       25.75  ...   
1907        24.75       24.50       23.50       24.50       25.00  ...   
1908        24.25       24.50       23.75       24.50       25.75  ...   
1909        25.00       24.50       23.75       24.75       25.50  ...   
1910        24.00       24.25       24.00       24.00       24.75  ...   
...           ...         ...         ...         ...         ...  ...   
9997        25.00       24.75       24.25       24.75       25.50  ...   
9998        25.00       24.25       24.00       25.00       24.75  ...   
9999        24.75       24.25       23.75       24.75       25.00  ...   
10000       24.00       25.00       23.25       24.00       25.50  ...   
10001       24.25       24.25       23.75       24.50       25.00  ...   

       thermal_55  thermal_56  thermal_57  thermal_58  thermal_59  thermal_60  \
True                                                                            
1906        23.50       25.25       24.50       25.25       24.75       25.25   
1907        23.00       25.50       24.00       25.00       24.75       25.25   
1908        24.00       24.75       24.25       24.75       24.75       24.50   
1909        24.00       25.00       24.00       25.25       24.75       24.50   
1910        24.25       24.00       25.00       24.75       24.50       24.50   
...           ...         ...         ...         ...         ...         ...   
9997        23.50       24.25       23.25       24.50       24.25       24.75   
9998        22.50       24.00       24.25       24.00       24.25       23.75   
9999        22.75       24.00       24.25       24.25       24.25       23.75   
10000       23.50       24.25       24.00       24.50       24.00       24.00   
10001       23.00       24.50       24.25       24.50       24.50       24.75   

       thermal_61  thermal_62  thermal_63    avg  
True                                              
1906        25.00       23.75       23.00  24.30  
1907        26.00       23.00       23.50  24.22  
1908        24.50       23.50       23.00  24.18  
1909        25.00       24.00       23.50  24.14  
1910        24.75       23.75       23.50  24.06  
...           ...         ...         ...    ...  
9997        24.50       23.50       22.50  24.10  
9998        24.50       22.25       23.00  23.94  
9999        24.75       22.75       22.75  23.98  
10000       24.25       22.50       21.75  23.84  
10001       25.00       22.75       22.75  24.06  

[8096 rows x 66 columns]

In [96]:
rscaler = MinMaxScaler()
tdf.iloc[:,:-1] = rscaler.fit_transform(tdf.iloc[:,:-1])

In [97]:
tdf.head()

sensor_degree  thermal_00  thermal_01  thermal_02  thermal_03  \
True                                                                  
1906            0.2        0.25        0.40    0.444444    0.421053   
1907            0.2        0.40        0.35    0.277778    0.263158   
1908            0.2        0.25        0.40    0.388889    0.421053   
1909            0.2        0.40        0.35    0.277778    0.263158   
1910            0.2        0.30        0.30    0.222222    0.210526   

      thermal_04  thermal_05  thermal_06  thermal_07  thermal_08  ...  \
True                                                              ...   
1906    0.315789    0.421053    0.500000    0.444444    0.473684  ...   
1907    0.368421    0.368421    0.318182    0.333333    0.315789  ...   
1908    0.263158    0.368421    0.363636    0.333333    0.473684  ...   
1909    0.421053    0.368421    0.363636    0.388889    0.421053  ...   
1910    0.210526    0.315789    0.409091    0.222222    0.263158  ...   

      thermal_56  thermal_57  thermal_58  thermal_59  thermal_60  thermal_61  \
True                                                                           
1906    0.464286    0.380952    0.409091    0.272727       0.375    0.347826   
1907    0.500000    0.285714    0.363636    0.272727       0.375    0.521739   
1908    0.392857    0.333333    0.318182    0.272727       0.250    0.260870   
1909    0.428571    0.285714    0.409091    0.272727       0.250    0.347826   
1910    0.285714    0.476190    0.318182    0.227273       0.250    0.304348   

      thermal_62  thermal_63       avg  staus  
True                                           
1906    0.346154    0.370370  0.494424      0  
1907    0.230769    0.444444  0.464684      0  
1908    0.307692    0.370370  0.449814      0  
1909    0.384615    0.444444  0.434944      0  
1910    0.346154    0.444444  0.405204      0  

[5 rows x 67 columns]

In [98]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

In [99]:
from sklearn.utils.discovery import *
from sklearn.metrics import *
import warnings
rets=all_estimators(type_filter='classifier')

In [100]:
train_data = tdf.iloc[:,:-1]
print(train_data.head())
train_label = tdf.iloc[:,-1]
print(train_label.head())

      sensor_degree  thermal_00  thermal_01  thermal_02  thermal_03  \
True                                                                  
1906            0.2        0.25        0.40    0.444444    0.421053   
1907            0.2        0.40        0.35    0.277778    0.263158   
1908            0.2        0.25        0.40    0.388889    0.421053   
1909            0.2        0.40        0.35    0.277778    0.263158   
1910            0.2        0.30        0.30    0.222222    0.210526   

      thermal_04  thermal_05  thermal_06  thermal_07  thermal_08  ...  \
True                                                              ...   
1906    0.315789    0.421053    0.500000    0.444444    0.473684  ...   
1907    0.368421    0.368421    0.318182    0.333333    0.315789  ...   
1908    0.263158    0.368421    0.363636    0.333333    0.473684  ...   
1909    0.421053    0.368421    0.363636    0.388889    0.421053  ...   
1910    0.210526    0.315789    0.409091    0.222222    0.263158

In [101]:
# result=[]
# for name, estimator_ in rets:
#     try:
#         model=estimator_()
#         if 'Logistic' in name or 'SGD' in name or 'MLP' in name:
#             model.set_params(max_iter=10000)
#         if 'SV' in name:
#             model.set_params(max_iter=100000, dual='auto')   
 
#         model.fit(train_data, train_label)
#         sc=model.score(train_data, train_label)
#         result.append((name, round(sc, 2)))
#     except Exception:
#         pass

In [102]:
# sorted(result, key=lambda x : x[1], reverse=True)
X_train, X_test, y_train, y_test =train_test_split(train_data,train_label)

In [103]:
def train_result(model):
    
    name = (str(model.__class__)).split('.')[3]
    # 학습
    model.fit(X_train, y_train)
    
    # 훈련 데이터와 테스트 데이터에서 정확도 계산
    train_score = model.score(X_train, y_train)
    test_score = model.score(X_test, y_test)

    # 예측값 계산
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    
    # 정확도 차이 계산
    diff = train_score - test_score
    
    # 평가 지표
    train_accuracy = accuracy_score(y_train, y_train_pred)
    test_accuracy = accuracy_score(y_test, y_test_pred)
    
    # F1-Score 등 더 상세한 평가 지표
    train_classification_report = classification_report(y_train, y_train_pred)
    test_classification_report = classification_report(y_test, y_test_pred)
    
    # 혼동 행렬
    train_confusion_matrix = confusion_matrix(y_train, y_train_pred)
    test_confusion_matrix = confusion_matrix(y_test, y_test_pred)
    
    # 결과 데이터프레임 준비
    resultDF = pd.DataFrame(columns=['train_score', 'test_score', 'diff', 
                                    'train_accuracy', 'test_accuracy'] )
                                    # 'train_classification_report', 'test_classification_report',
                                    # 'train_confusion_matrix', 'test_confusion_matrix'])
    resultDF.loc[name] = [train_score, test_score, diff, 
                            train_accuracy, test_accuracy]
    print('train_classification_report')
    print(train_classification_report)
    print('test_classification_report')
    print(test_classification_report)
    print('train_confusion_matrix')
    print(train_confusion_matrix)
    print('test_confusion_matrix')
    print(test_confusion_matrix)
    
    return model, resultDF

In [104]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
def gridCV_(model, param):
    ## 교차검증 및 튜닝 진행 인스턴스 생성
    # GridSearchCV는 모든 파라미터 조합을 시도합니다.
    # cv: 교차 검증 폴드 수 (일반적으로 3, 5, 10 등)
    # n_jobs: 병렬 처리할 작업 수 (-1은 모든 코어 사용)
    # verbose: 진행 상황 출력 레벨 (0: 출력 안 함, 1: 간략하게, 2: 상세하게)
    # error_score: 에러 발생 시 처리 방법 ('raise' 또는 특정 숫자)
    gridCV = GridSearchCV(model, param, refit=True, cv=5, n_jobs=-1, verbose=2, error_score='raise')
    print("구성된 하이퍼파라미터 탐색 범위:")
    for key, value in param.items():
        print(f"- {key}: {value}")
        
    gridCV.fit(X_train, y_train) # 학습 데이터로 최적의 파라미터를 찾습니다.
    print("--- GridSearchCV 모델 학습 완료 ---")
    print("-" * 30)

    # 4. 최적의 하이퍼파라미터 및 최고 성능 확인
    # -----------------------------------------------------------------------------
    print("\n--- 최적의 하이퍼파라미터 조합 ---")
    best_params = gridCV.best_params_
    print(best_params)

    print("\n--- 최적 모델의 교차 검증 최고 점수 ---")
    best_score = gridCV.best_score_
    print(f"정확도: {best_score:.4f}")
    print("-" * 30)

    # 5. 최적의 모델로 예측 및 성능 평가
    # -----------------------------------------------------------------------------
    # gridCV.best_estimator_에 refit=True 옵션 덕분에 최적의 파라미터로 학습된 모델이 저장됩니다.
    best_model = gridCV.best_estimator_

    print("\n--- 최적 모델로 테스트 데이터 예측 및 평가 ---")
    y_pred_test = best_model.predict(X_test)

    # 정확도
    test_accuracy = accuracy_score(y_test, y_pred_test)
    print(f"테스트 세트 정확도: {test_accuracy:.4f}")

    # 혼동 행렬
    test_confusion_matrix = confusion_matrix(y_test, y_pred_test)
    print("\n테스트 세트 혼동 행렬:")
    print(test_confusion_matrix)

    # 분류 보고서 (정밀도, 재현율, F1-스코어 등)
    test_classification_report = classification_report(y_test, y_pred_test)
    print("\n테스트 세트 분류 보고서:")
    print(test_classification_report)
    print("-" * 30)

    # 6. 결과 데이터프레임에 저장 (이전 질문의 코드 재활용)
    # -----------------------------------------------------------------------------
    # resultDF 초기화 (없을 경우 새로 생성)
    try:
        if not isinstance(resultDF, pd.DataFrame):
            raise NameError # DataFrame이 아니면 NameError 발생시켜 새로 생성
    except NameError:
        resultDF = pd.DataFrame(columns=['train_score', 'test_score', 'diff',
                                        'train_accuracy', 'test_accuracy',
                                        'train_classification_report', 'test_classification_report',
                                        'train_confusion_matrix', 'best_params']) # confusion_matrix는 dict 타입이 아니므로 주의
                                                                                # 여기서는 best_params를 추가함

    name = f"{str(model.__class__).split('.')[3]}_GridSearch_Best_{best_score:.4f}" # 모델 이름에 최고 점수 포함

    # GridSearchCV 결과에서 train_score는 gridCV.best_score_ (교차 검증 평균)가 됩니다.
    train_score_cv = gridCV.best_score_
    train_accuracy_cv = best_model.score(X_train, y_train) # 훈련 세트에서의 최종 모델 정확도

    diff = train_score_cv - test_accuracy

    # confusion matrix는 DataFrame에 직접 넣기보다 문자열로 변환하거나 별도로 저장하는 것이 좋습니다.
    # 여기서는 간단히 문자열로 변환합니다.
    test_confusion_matrix_str = str(test_confusion_matrix)
    # classification_report도 문자열로 변환합니다.
    train_classification_report_str = str(classification_report(y_train, best_model.predict(X_train)))
    test_classification_report_str = str(test_classification_report)


    resultDF.loc[name] = [train_score_cv, test_accuracy, diff,
                            train_accuracy_cv, test_accuracy,
                            train_classification_report_str, test_classification_report_str,
                            test_confusion_matrix_str, best_params]

    print("\n--- 결과 데이터프레임 (resultDF) ---")
    print(resultDF.transpose()) # 보기 좋게 전치하여 출력
    print("-" * 30)

In [105]:
param_dt = {
    # 불순도 측정 기준
    'criterion': ['gini', 'entropy', 'log_loss'],

    # 노드 분할 전략
    'splitter': ['best', 'random'],

    # 트리의 최대 깊이: 너무 깊으면 과적합, 너무 얕으면 과소적합.
    # 일반적으로 5 ~ 30 사이의 값을 많이 탐색합니다.
    'max_depth': [16, 24, 32], # 5부터 30까지의 정수 (포함)

    # 노드를 분할하기 위한 최소 샘플 수: int 또는 float
    # float인 경우 전체 샘플 수에 대한 비율
    # 'min_samples_split': [2, 4, 0.05, 0.1], # 정수 값과 비율을 함께 탐색
    'min_samples_split': [2, 4], # 정수 값과 비율을 함께 탐색

    # 리프 노드가 되기 위한 최소 샘플 수: int 또는 float
    # 'min_samples_leaf': [1, 2, 4, 0.01, 0.05], # 정수 값과 비율을 함께 탐색
    'min_samples_leaf': [1, 2, 4], # 정수 값과 비율을 함께 탐색

    # 리프 노드에 필요한 최소 가중치 샘플 비율
    'min_weight_fraction_leaf': [0.0, 0.001, 0.01],

    # 최적의 분할을 찾을 때 고려할 특성(feature)의 수
    # 'sqrt'는 sqrt(n_features)를 의미하며, 'log2'는 log2(n_features)를 의미
    'max_features': ['sqrt', 'log2'], # 'auto'는 1.1부터 'sqrt'와 동일 (현재는 'sqrt'로 리디렉션됨)
                                           # None은 모든 특성 사용

    # 리프 노드의 최대 개수
    # None은 제한 없음. 적절한 범위를 설정하여 탐색
    'max_leaf_nodes': [None, 20, 50, 100], # None과 함께 특정 숫자들을 탐색

    # 불순도 감소 최소량: 이 값보다 불순도 감소량이 작으면 노드 분할 중단
    'min_impurity_decrease': [0.005, 0.01, 0.02],

    # 복잡도 매개변수 (가지치기)
    'ccp_alpha': [0.01, 0.05] # 0.0은 가지치기 없음                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
}

## 모델 인스턴스 생성
dtmodel = DecisionTreeClassifier(random_state=42)

# gridCV_(dtmodel, param_dt)

In [106]:
dtCmodel = DecisionTreeClassifier(ccp_alpha= 0.01, criterion= 'gini', max_depth= 16, max_features= 'log2', max_leaf_nodes= 20, min_impurity_decrease= 0.005, min_samples_leaf= 1, min_samples_split= 2, min_weight_fraction_leaf= 0.0, splitter= 'best')
train_result(dtCmodel)


train_classification_report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00      1507
           1       0.00      0.00      0.00      1494
           2       0.51      1.00      0.67      3071

    accuracy                           0.51      6072
   macro avg       0.17      0.33      0.22      6072
weighted avg       0.26      0.51      0.34      6072

test_classification_report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       493
           1       0.00      0.00      0.00       529
           2       0.50      1.00      0.66      1002

    accuracy                           0.50      2024
   macro avg       0.17      0.33      0.22      2024
weighted avg       0.25      0.50      0.33      2024

train_confusion_matrix
[[   0    0 1507]
 [   0    0 1494]
 [   0    0 3071]]
test_confusion_matrix
[[   0    0  493]
 [   0    0  529]
 [   0    0 1002]]


c:\Users\Administrator\anaconda3\envs\test310\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Administrator\anaconda3\envs\test310\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Administrator\anaconda3\envs\test310\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitaliz

(DecisionTreeClassifier(ccp_alpha=0.01, max_depth=16, max_features='log2',
                        max_leaf_nodes=20, min_impurity_decrease=0.005),
                           train_score  test_score      diff  train_accuracy  \
 DecisionTreeClassifier'>     0.505764    0.495059  0.010705        0.505764   
 
                           test_accuracy  
 DecisionTreeClassifier'>       0.495059  )

In [122]:
param_rf = {
    # Random Forest 고유 파라미터 ------------------------------------------------
    # 앙상블에 사용할 트리의 개수: 모델의 복잡도와 안정성에 영향
    'n_estimators': [500], # 일반적으로 100~500 사이의 값을 많이 탐색
                                         # 너무 크면 학습 시간이 오래 걸림

    # 부트스트랩 샘플링 사용 여부 (True가 기본값이며 일반적)
    'bootstrap': [True],

    # Decision Tree 파라미터 (Random Forest도 내부적으로 Decision Tree를 사용) -----------
    # 불순도 측정 기준
    'criterion': ['gini', 'entropy', 'log_loss'],

    # 트리의 최대 깊이: 너무 깊으면 과적합, 너무 얕으면 과소적합.
    # Random Forest는 개별 트리의 깊이보다는 트리의 개수가 더 중요할 수 있으나,
    # 깊이 제한을 통해 과적합 방지 및 속도 개선 가능
    'max_depth': [40, 50], # None은 제한 없음. 10단위로 탐색

    # 노드를 분할하기 위한 최소 샘플 수: int 또는 float (비율)
    'min_samples_split': [2, 5],

    # 리프 노드가 되기 위한 최소 샘플 수: int 또는 float (비율)
    'min_samples_leaf': [1, 2],

    # 최적의 분할을 찾을 때 고려할 특성(feature)의 수
    # 'sqrt'는 sqrt(n_features)를 의미 (기본값), 'log2'는 log2(n_features)를 의미
    # Random Forest는 무작위로 특성을 선택하여 다양성을 확보하므로 중요
    'max_features': ['sqrt', 'log2'], # 'auto'는 1.1부터 'sqrt'와 동일 (현재는 'sqrt'로 리디렉션됨)
                                           # None은 모든 특성 사용 (과적합 위험 증가)

    # 리프 노드의 최대 개수
    'max_leaf_nodes': [None, 20, 50, 100],

    # 불순도 감소 최소량: 이 값보다 불순도 감소량이 작으면 노드 분할 중단
    'min_impurity_decrease': [0.001, 0.002],

    # 복잡도 매개변수 (가지치기)
    'ccp_alpha': [0.001, 0.002] # 0.0은 가지치기 없음
}


## 모델 인스턴스 생성
rfmodel = RandomForestClassifier(random_state=42)

gridCV_(rfmodel, param_rf)

구성된 하이퍼파라미터 탐색 범위:
- n_estimators: [500]
- bootstrap: [True]
- criterion: ['gini', 'entropy', 'log_loss']
- max_depth: [40, 50]
- min_samples_split: [2, 5]
- min_samples_leaf: [1, 2]
- max_features: ['sqrt', 'log2']
- max_leaf_nodes: [None, 20, 50, 100]
- min_impurity_decrease: [0.001, 0.002]
- ccp_alpha: [0.001, 0.002]
Fitting 5 folds for each of 768 candidates, totalling 3840 fits
--- GridSearchCV 모델 학습 완료 ---
------------------------------

--- 최적의 하이퍼파라미터 조합 ---
{'bootstrap': True, 'ccp_alpha': 0.001, 'criterion': 'entropy', 'max_depth': 40, 'max_features': 'sqrt', 'max_leaf_nodes': None, 'min_impurity_decrease': 0.001, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 500}

--- 최적 모델의 교차 검증 최고 점수 ---
정확도: 0.9081
------------------------------

--- 최적 모델로 테스트 데이터 예측 및 평가 ---
테스트 세트 정확도: 0.9046

테스트 세트 혼동 행렬:
[[414  22  57]
 [ 45 446  38]
 [ 14  17 971]]

테스트 세트 분류 보고서:
              precision    recall  f1-score   support

           0       0.88      0.84      0.86   

In [ ]:
{'bootstrap': True, 'ccp_alpha': 0.001, 'criterion': 'entropy', 'max_depth': 40, 'max_features': 'sqrt', 'max_leaf_nodes': None, 'min_impurity_decrease': 0.001, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 500}


In [123]:
rfm50 = RandomForestClassifier(bootstrap= True, ccp_alpha= 0.0001, criterion= 'entropy', max_depth= 100, max_features= 'log2', max_leaf_nodes= None, min_impurity_decrease= 0.001, min_samples_leaf= 1, min_samples_split= 2, n_estimators= 1000)
best_rfm50, resultDF= train_result(rfm50)

train_classification_report
              precision    recall  f1-score   support

           0       0.98      0.93      0.96      1507
           1       1.00      0.97      0.98      1494
           2       0.96      1.00      0.98      3071

    accuracy                           0.97      6072
   macro avg       0.98      0.97      0.97      6072
weighted avg       0.97      0.97      0.97      6072

test_classification_report
              precision    recall  f1-score   support

           0       0.85      0.85      0.85       493
           1       0.93      0.83      0.88       529
           2       0.91      0.97      0.94      1002

    accuracy                           0.90      2024
   macro avg       0.90      0.88      0.89      2024
weighted avg       0.90      0.90      0.90      2024

train_confusion_matrix
[[1406    3   98]
 [  19 1450   25]
 [  11    0 3060]]
test_confusion_matrix
[[419  17  57]
 [ 53 439  37]
 [ 20  14 968]]


In [124]:
resultDF

train_score  test_score      diff  train_accuracy  \
RandomForestClassifier'>     0.974308    0.902174  0.072134        0.974308   

                          test_accuracy  
RandomForestClassifier'>       0.902174

In [125]:
rfm = RandomForestClassifier(bootstrap= True, ccp_alpha= 0.001, criterion= 'entropy', max_depth= 40, max_features= 'log2', max_leaf_nodes= None, min_impurity_decrease= 0.001, min_samples_leaf= 1, min_samples_split= 2, n_estimators= 500)
best_rfm, resultDF= train_result(rfm)


train_classification_report
              precision    recall  f1-score   support

           0       0.98      0.93      0.95      1507
           1       1.00      0.97      0.98      1494
           2       0.96      1.00      0.98      3071

    accuracy                           0.97      6072
   macro avg       0.98      0.97      0.97      6072
weighted avg       0.97      0.97      0.97      6072

test_classification_report
              precision    recall  f1-score   support

           0       0.85      0.85      0.85       493
           1       0.93      0.84      0.88       529
           2       0.91      0.97      0.94      1002

    accuracy                           0.90      2024
   macro avg       0.90      0.88      0.89      2024
weighted avg       0.90      0.90      0.90      2024

train_confusion_matrix
[[1409    2   96]
 [  25 1442   27]
 [  10    0 3061]]
test_confusion_matrix
[[418  18  57]
 [ 52 442  35]
 [ 20  14 968]]


In [126]:
resultDF

train_score  test_score      diff  train_accuracy  \
RandomForestClassifier'>      0.97365    0.903162  0.070487         0.97365   

                          test_accuracy  
RandomForestClassifier'>       0.903162

In [127]:
testData = pd.DataFrame(pd.read_csv('../thermal_data.csv', index_col=1))
testData = testData.drop(columns=['timestamp', 'etc_1', 'etc_2'])
print(testData.shape)
testData.insert(65, 'avg', 0, allow_duplicates=False )

(4709, 65)


In [113]:
testData.index

Index([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
       ...
       4700, 4701, 4702, 4703, 4704, 4705, 4706, 4707, 4708, 4709],
      dtype='int64', name='packet_id', length=4709)

In [114]:
testData.head()

sensor_degree  thermal_00  thermal_01  thermal_02  thermal_03  \
packet_id                                                                  
1                29.4375       24.75       24.75       25.25       25.00   
2                29.3750       24.00       24.75       24.25       25.25   
3                29.4375       24.50       24.25       24.75       25.00   
4                29.3750       22.75       24.25       24.25       24.50   
5                29.3750       24.00       23.75       24.50       24.75   

           thermal_04  thermal_05  thermal_06  thermal_07  thermal_08  ...  \
packet_id                                                              ...   
1               25.00       24.75       25.25       26.50       25.75  ...   
2               24.50       24.50       24.75       25.25       25.00  ...   
3               24.75       25.25       25.25       25.50       25.25  ...   
4               24.50       24.00       24.00       24.25       24.25  ...   
5               24.50       24.25       24.25       24.50       25.25  ...   

           thermal_55  thermal_56  thermal_57  thermal_58  thermal_59  \
packet_id                                                               
1               25.75       26.50       25.50       26.50       26.75   
2               26.00       27.25       26.00       26.75       26.75   
3               25.50       26.00       26.00       26.25       26.50   
4               25.25       26.00       26.00       26.75       26.50   
5               25.25       26.50       25.25       26.25       26.00   

           thermal_60  thermal_61  thermal_62  thermal_63  avg  
packet_id                                                       
1               26.75       27.50       25.75       26.25    0  
2               26.75       26.75       25.50       25.75    0  
3               26.75       27.00       25.25       26.00    0  
4               26.50       26.75       25.25       26.00    0  
5               26.25       26.75       25.50       26.00    0  

[5 rows x 66 columns]

In [115]:
testData.iloc[0, 0]

np.float64(29.4375)

In [117]:
for x in range(len(testData.index)):
    testData.iloc[x, 65] = round(testData.iloc[x,1:65].mean(),2)
testData.head()


sensor_degree  thermal_00  thermal_01  thermal_02  thermal_03  \
packet_id                                                                  
1                29.4375       24.75       24.75       25.25       25.00   
2                29.3750       24.00       24.75       24.25       25.25   
3                29.4375       24.50       24.25       24.75       25.00   
4                29.3750       22.75       24.25       24.25       24.50   
5                29.3750       24.00       23.75       24.50       24.75   

           thermal_04  thermal_05  thermal_06  thermal_07  thermal_08  ...  \
packet_id                                                              ...   
1               25.00       24.75       25.25       26.50       25.75  ...   
2               24.50       24.50       24.75       25.25       25.00  ...   
3               24.75       25.25       25.25       25.50       25.25  ...   
4               24.50       24.00       24.00       24.25       24.25  ...   
5               24.50       24.25       24.25       24.50       25.25  ...   

           thermal_55  thermal_56  thermal_57  thermal_58  thermal_59  \
packet_id                                                               
1               25.75       26.50       25.50       26.50       26.75   
2               26.00       27.25       26.00       26.75       26.75   
3               25.50       26.00       26.00       26.25       26.50   
4               25.25       26.00       26.00       26.75       26.50   
5               25.25       26.50       25.25       26.25       26.00   

           thermal_60  thermal_61  thermal_62  thermal_63    avg  
packet_id                                                         
1               26.75       27.50       25.75       26.25  25.50  
2               26.75       26.75       25.50       25.75  25.23  
3               26.75       27.00       25.25       26.00  25.18  
4               26.50       26.75       25.25       26.00  24.81  
5               26.25       26.75       25.50       26.00  24.96  

[5 rows x 66 columns]

In [120]:
best_rfm.predict(testData.iloc[0,:].values.reshape(1,-1))

c:\Users\Administrator\anaconda3\envs\test310\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([2])